spring.application.name=cloudtestapp
server.port=${PORT:8082}

spring.datasource.url=${DB_URL:jdbc:mysql:///cloudtaskdb?cloudSqlInstance=cloud-task-manager-gcp:us-central1:free-trial-first-project&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true